### ISSUE TITLE
Proactive control

### ISSUE THREAD

**Issue by Galvin-wjw** [aws-samples/aws-control-tower-controls-terraform#1] opened 2023-07-03 08:45 UTC
For the proactive control,  CT.CLOUDFORMATION.PR.1 is the prerequisite.

But when I config tfvars like the below:
```
 {
    control_names = [
      "AWS-GR_SUBNET_AUTO_ASSIGN_PUBLIC_IP_DISABLED",
      "VQJENYWQLIKN", // prerequisite control CT.CLOUDFORMATION.PR.1
      "LZMEYSKSQSYC" //"CT.EC2.PR.3"Require that any Amazon EC2 security group rule does not use the source IP range 0.0.0.0/0 or ::/0 for ports other than 80 and 443
    ],
    organizational_unit_ids = ["ou-XXX"],
```

Terraform apply also returns 
```
ValidationException: AWS Control Tower cannot enable the control CT.EC2.PR.3 on ou-xXX, because the prerequisite control CT.CLOUDFORMATION.PR.1 is not enabled for this OU.
```

I need to apply again to compete the configuration, Is it possible to add some process to handle this situation？

Maybe add prerequisite before the guardrails creation.
```
 resource "aws_controltower_control" "guardrails"
```

**Comment by ikerei** [comment] 2023-07-06 09:08
Hi @Galvin-wjw thank you for raising the ticket. Currently this option is not supported, for the use of proactive controls it is required to apply the implementation of the CT.CLOUDFORMATION.PR.1 prerequisite before deploying the CTC module. 
This can be done in several ways for example using the Console or the API with the CTC tool deployed in a previous step of the CI/CD pipeline. We are working on the new feature to add this optional prerequisite in the module’s configuration.
Additional information on this prerequisite is in the AWS documentation https://docs.aws.amazon.com/controltower/latest/userguide/proactive-controls.html.

**Comment by SumanthYR** [comment] 2024-11-22 14:45
Hi, is the issue mentioned above still active?

I am encountering an API error while attempting to apply the prerequisite control "CT.CLOUDFORMATION.PR.1." 

```
Error: creating ControlTower Control (arn:aws:organizations::123456789:ou/o-****/ou-aj*****,arn:aws:controlcatalog:::control/zafyxpgsg1ck4b99fc0197sk,arn:aws:controltower:us-east-1::control/CT.CLOUDFORMATION.PR.1): operation error ControlTower: EnableControl, https response error StatusCode: 400, RequestID: 5fe1d35b-62a7-4507-9b44-0e8a74d31195, api error BadRequestException: Invalid request body

**Comment by ikerei** [comment] 2024-11-29 14:19
The issue you have is different from the one above because you got 400 error invalid request body. The error above is related to the prerequisite CT.CLOUDFORMATION.PR.1 that is not enabled.

Can you please share the configuration file to allow us to reproduce the issue?

Please be aware that there is a recent release of new control API identifiers here https://docs.aws.amazon.com/controltower/latest/controlreference/all-global-identifiers.html (global API identifiers).

From your logs it seems you are using a mix of old API identifiers and new API identifiers and this could be the reason.
Can you please try to use only global api identifiers?

We are working on providing updated doc asap.

Thank you very much for your help and feedback.

**Comment by ikerei** [comment] 2024-11-29 14:38
We are releasing a new version of the pattern to support the new global control identifiers documented here:
https://docs.aws.amazon.com/controltower/latest/controlreference/all-global-identifiers.html

**Comment by igirardi** [comment] 2024-12-19 14:16
@SumanthYR thank you for the feedback. This should be fixed with PR https://github.com/aws-samples/aws-control-tower-controls-terraform/pull/4.

**Closed by igirardi** 2024-12-19 14:16 UTC
Labels: enhancement

**Comment by SumanthYR** [comment] 2024-12-25 12:13
Hi Ikerei,

Thanks, Its working after replacing the identifier with WTDSMKDKDNLE
